name: SpinSym
version: 1.5
date: 2013-02-01
description: |
    Brauer tables of spin-symmetric groups

authors:
    - name: Lukas Maas
      url: http://www.uni-due.de/~s400304

maintainers:
    - name: Lukas Maas
      url: http://www.uni-due.de/~s400304

GAP: ">=4.5"

needed-pkgs:
    - name: "CTblLib"
      version: ">=1.2.2"
      url: "http://www.math.rwth-aachen.de/~Thomas.Breuer/ctbllib"
    - name: "GAPDoc"
      version: ">=1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://www.uni-due.de/~s400304/spinsym/
readme: README
packageinfo: http://www.uni-due.de/~s400304/spinsym/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www.uni-due.de/~s400304/spinsym/pkg/spinsym-1.5.tar.gz

abstract: |
    This package contains Brauer tables of Schur covers of symmetric and alternating groups, and provides some related functionalities.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    spin, projective, symmetric group, alternating group, Schur cover, double cover, Young.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Maa13</span>]   <b class='BibAuthor'>Maas, L.</b>,
     <i class='BibTitle'>SpinSym, Brauer tables of spin-symmetric groups,
             Version 1.5</i>
     (<span class='BibYear'>2013</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="http://www.uni-due.de/~s400304/spinsym/">http://www.uni-due.de/~s400304/spinsym/</a></span>.
    </p>
    

bibtex: |
    @misc{ SpinSym1.5,
      author =           {Maas, L.},
      title =            {{SpinSym}, Brauer tables of spin-symmetric groups, {V}ersion 1.5},
      month =            {Feb},
      year =             {2013},
      note =             {GAP package},
      howpublished =     {\href                             {http://www.uni-due.de/~s400304/spinsym/}                             {\texttt{http://www.uni-due.de/}\discretionary
                          {}{}{}\texttt{\texttt{\symbol{126}}s400304/}\discretionary {}{}{}\texttt{spinsym/}}},
      keywords =         {spin; projective; symmetric group; alternating group; Schur cover; double cover; Young},
      printedkey =       {Maa13}
    }

